baseURL = "http://xianyuluo.com"
languageCode = "cn-ZH"
title = "xianyuLuo Blog"
themes = "maupassant"
enableEmoji = "true"
summaryLength = 40

[author]
  name = "xianyuLuo"

[params]
  author = "xianyuLuo"
  subtitle = "当你的才华还不能支撑起你的野心时，你应该静下心来，好好学习！"
  keywords = "python,运维,Kubernetes,Istio,ServiceMesh,xianyuLuo,博客,python,软件架构,公众号"
  description = "当你的才华还不能支撑起你的野心时，你应该静下心来，好好学习！"
  GitHubUser = "xianyuLuo"

[params.utteranc]
  enable = true
  repo = "xianyuLuo/utterances"    # 存储评论的Repo，格式为 owner/repo
  issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
  theme = "github-light" # 样式主题，有github-light和github-dark两种
  crossorigin="anonymous"

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4
